In [1]:
import numpy as np

In [2]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
arr_2d[1][1]

25

In [7]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [8]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [9]:
arr=np.arange(1,11)

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [13]:
bool_arr=arr>5

In [14]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [15]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [16]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [17]:
arr[arr<3]

array([1, 2])

In [18]:
arr_2d=np.arange(50).reshape(5,10)

In [19]:
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [22]:
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [25]:
arru=arr_2d.reshape(25,2)

In [26]:
arru

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [27]:
arru=arr_2d.reshape(2,25)

In [28]:
arru

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.random.rand(1)

array([0.51097541])

In [32]:
np.random.randn(25)

array([ 0.3091735 ,  0.41429286,  0.44251916, -0.73028511, -2.27316943,
        0.22457483, -0.33505452, -0.04636217, -0.37992487,  0.69792291,
       -0.79327919, -0.17571277,  2.29218789, -0.21017329, -0.12045096,
       -0.18415212, -0.71378415, -0.36577578, -0.16094713, -1.48700894,
        0.33438041,  0.33066383,  1.31585876,  0.34108816, -0.44315509])

In [33]:
arru.std


<function ndarray.std>

In [34]:
arru.std()

14.430869689661812

In [35]:
arru.sum(axis=0)

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73])

In [36]:
arru

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
arru.sum[axis=1]

SyntaxError: invalid syntax (<ipython-input-38-909cc2a6e6c1>, line 1)